# syntax=docker/dockerfile:1.4

FROM notiesu/crbot-base:latest

USER root

ENV VOLUME_DIR="/runpod-volume"
ENV PATH=/opt/conda/bin:$PATH

RUN mkdir -p ${VOLUME_DIR} && chown -R mambauser ${VOLUME_DIR}

COPY --chown=mambauser:mambauser . .
# Entrypoint

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
COPY api-train.sh /api-train.sh
RUN chmod +x /api-train.sh
ENTRYPOINT ["/entrypoint.sh"]
